services:
  #  spring-app:

 # https://hub.docker.com/r/bitnami/minio
 # https://github.com/bitnami/containers/blob/main/bitnami/minio/docker-compose.yml
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'

  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: boki_portfolio
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

volumes:
  mysql-data:
  minio_data:
    driver: local
