spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
#      location: /users/boki/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 5MB # 개별 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 20MB # 전체 요청의 최대 사이즈 (default: 10MB)
