spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
        connection:
          characterEncoding: utf-8
          useUnicode: true
          CharSet: utf-8
        jdbc:
          time_zone: UTC
          batch_size: 50
        show_sql: false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        order_inserts: true
        order_updates: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _AUDIT_LOG
    show-sql: false
    open-in-view: off

---

spring:
  config.activate.on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
