springdoc:
  api-docs:
    path: /api/docs:json

  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    groups-order: desc
    disable-swagger-default-url: true
    query-config-enabled: true
    use-root-path: false
    path: /api/docs:ui
