server:
  port: 8090
  shutdown: graceful
  error.whitelabel.enabled: false

spring:
  application:
    name: boki-portfolio
  profiles:
    active: dev
    include: datasource, jpa, logging, swagger, actuator, servlet, redis

boki:
  token:
    secret: ${jwt-secret}
  minio:
    endpoint: "http://localhost:9000"
#    bucket-name: "code-boki"
    bucket-name: "test"
    access-key: u3wwfzmm1esw9NrSLBKo
    secret-key: 9uqqlMo4ULvrU2Jjmkls4Jhmx5Nwnqwu06f9kdAT
