@protocol = http
@myhost = localhost:8080
@target = {{protocol}}://{{myhost}}
@auth_endpoint = {{protocol}}://{{myhost}}/api/auth

// @no-log

// @no-cookie-jar

### 회원가입
# with validation
POST {{auth_endpoint}}/signup
Content-Type: application/json

{
    "email": "hello@test.com",
    "phoneNumber": "010-7777-5678",
    "userId":  "Tester1",
    "name": "이승복",
    "password":  "Password12345!@"
}

### 로그인
POST {{auth_endpoint}}/login
Content-Type: application/json

{
    "userId":  "Tester1",
    "password":  "Password12345!@"
}
